// Include Sapiens headers so bindgen has everything available
#include "../../../extern/sapiens-mod-creation/SPlugins/include/SPBiome.h"
#include "../../../extern/sapiens-mod-creation/SPlugins/include/SPClimate.h"
#include "../../../extern/sapiens-mod-creation/SPlugins/include/SPCommon.h"
#include "../../../extern/sapiens-mod-creation/SPlugins/include/SPHeight.h"
#include "../../../extern/sapiens-mod-creation/SPlugins/include/SPMath.h"
#include "../../../extern/sapiens-mod-creation/SPlugins/include/SPNoise.h"
#include "../../../extern/sapiens-mod-creation/SPlugins/include/SPParticles.h"
#include "../../../extern/sapiens-mod-creation/SPlugins/include/SPRainfall.h"
#include "../../../extern/sapiens-mod-creation/SPlugins/include/SPRand.h"