pipeline {
    parameters {
        booleanParam(name: 'Publish', defaultValue: false, description: 'Whether to publish the crate to crates.io')
    }

    agent any

    stages {
        // Regenerates the FFI bindings and increments the package version number
        stage('Regenerate Bindings') {
            steps {
                powershell '''cd sapiens-sys

                # Generate bindings
                .\New-Bindings.ps1

                # Commit results
                git add Cargo.toml
                git commit -m "Increment version"
                git push origin HEAD:master
                '''
            }
        }

        // Compiles the FFI bindings into a crate
        stage('Build') {
            steps {
                powershell "cargo build --name sapiens-sys"
            }
        }

        // Publishes new version of bindings
        stage('Publish') {
            when {
                expression { Publish == true }
            }

            steps {
                powershell "echo Publishing"
            }
        }
    }
}